# Generated by Django 3.2.5 on 2021-07-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='institutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=500)),
                ('institution', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('province', models.CharField(max_length=500)),
            ],
        ),
    ]
