# Generated by Django 3.2.5 on 2021-07-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_remove_institutions_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='city',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='institution',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='province',
            field=models.TextField(max_length=500),
        ),
    ]
