# Generated by Django 3.2.5 on 2021-07-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_majors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='institutions',
            new_name='universities',
        ),
    ]
