# Generated by Django 3.2.5 on 2021-07-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_rename_institutions_universities'),
    ]

    operations = [
        migrations.CreateModel(
            name='fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agricultural', models.TextField(max_length=500)),
                ('Art', models.TextField(max_length=500)),
                ('Biological', models.TextField(max_length=500)),
                ('Chemical', models.TextField(max_length=500)),
                ('Commerce', models.TextField(max_length=500)),
                ('Computer', models.TextField(max_length=500)),
                ('Earth', models.TextField(max_length=500)),
                ('Engineering', models.TextField(max_length=500)),
                ('Management', models.TextField(max_length=500)),
                ('Media', models.TextField(max_length=500)),
                ('Medical', models.TextField(max_length=500)),
                ('Physics', models.TextField(max_length=500)),
                ('Religious', models.TextField(max_length=500)),
                ('Social', models.TextField(max_length=500)),
                ('Technical', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='majors',
        ),
    ]
