# Generated by Django 3.2.5 on 2021-07-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0006_auto_20210724_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='Agricultural',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Art',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Biological',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Chemical',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Commerce',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Computer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Earth',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Engineering',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Management',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Media',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Medical',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Physics',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Religious',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Social',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Technical',
            field=models.CharField(max_length=500),
        ),
    ]
